version: '3'
services:
  mongo:
    image: mongo
    container_name: springboot-mongo
    ports:
      - 27018:27017
    volumes:
    - $HOME/data/springboot-mongo-data:/data/db
    - $HOME/data/springboot-mongo-bkp:/data/bkp
    - ../MongoSeed/scripts/:/scripts
    restart: always
  videochat:
    image: videochat_image
    build: ../Twilio
    container_name: videochat
    volumes:
      - '../Twilio:/code'
    ports:
      - '3000:3000'
  teacher:
    build: ../Teacher
    restart: always
    container_name: teacher_image
    ports:
      - 3001:3001
    working_dir: /opt/app
    depends_on:
    - mongo